### ISSUE TITLE
update for 1.0?

### ISSUE THREAD

**Issue by Cadair** [conda-forge/jupyter-book-feedstock#24] opened 2024-02-20 11:29 UTC
### Comment:

Hello :wave: I was just wondering if there was anything holding up bumping the feedstock to the 1.0 release?

**Comment by bollwyvl** [comment] 2024-02-21 13:24
Fixed by #26. Please pardon the delay. :blush:

The root cause was the PyPI `sdist` changed its name (`_`, not `-`), which prevented the bot from fetching it and therefore starting a PR. Then there was a missing related dependency build (which also failed to bot PR due to pep-517-build-system-of-the-week issues), and finally a patch was needed for building against python 3.12 (use of deprecated APIs).

**Closed as completed by bollwyvl** 2024-02-21 13:24 UTC
Labels: question
